---
id: 27fa940238
question: Problem with importing the dlt or dlt.sources module
sort_order: 4440
---

Make sure you donâ€™t have a `dlt.py` file saved in the same directory as your working file.